// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rxmytjfyfmhynknchelc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ4bXl0amZ5Zm1oeW5rbmNoZWxjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY5NDAyMjksImV4cCI6MjA3MjUxNjIyOX0.M3rpVvneSsc7tAaZeidcss3yiWL6PMQB9r1tpj536js";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});